version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  environment:
    RUBY_VERSION: "2.6.10"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chefstyle
    versions:
    - "> 0.4.0"
  - dependency-name: cucumber
    versions:
    - 5.3.0
  - dependency-name: contracts
    versions: [">= 0.17.0"] # 0.16 is the last version to do ruby < 3
  - dependency-name: pry-stack_explorer
    versions:
    - 0.6.0
    - 0.6.1
