source "https://rubygems.org"

gem "mixlib-install", path: "../"
gem "test-kitchen", github: "sersut/test-kitchen", branch: "sersut/mixlib-install-update"
gem "chef-acceptance", github: "chef/chef-acceptance"
gem "pry"

group(:development) do
  gem "kitchen-vagrant"
  gem "windows_chef_zero"
  gem "winrm-transport"
end
