source "https://rubygems.org"

gem "mixlib-install", path: "../"
gem "test-kitchen", github: "sersut/test-kitchen"
gem "chef-acceptance", github: "chef/chef-acceptance"
gem "pry"

group(:development) do
  gem "kitchen-vagrant"
end
