source "https://rubygems.org"

gem "mixlib-install", path: "../"
gem "test-kitchen", path: "../../test-kitchen"
gem "chef-acceptance", github: "chef/chef-acceptance", branch: "pw/commands"
gem "pry"

group(:development) do
  gem "kitchen-vagrant"
end
